name: Build and Deploy auth-users-service (ARM64)

on:
  push:
    branches: [ "MTC-201" ]
    paths:
      - 'backend/auth-users-service/**'
      - '.github/workflows/auth-service-ci.yml'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get version (use Git SHA as tag)
        id: vars
        run: echo "TAG=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push ARM64 image
        uses: docker/build-push-action@v4
        with:
          context: ./backend/auth-users-service
          platforms: linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/auth-users-service:${{ steps.vars.outputs.TAG }}

      - name: Update image tag in GitOps repository
        uses: peter-evans/find-replace-action@v2
        with:
          repository: andresl123/food-rescue-gitops
          token: ${{ secrets.GITOPS_REPO_TOKEN }}

          find: "image: ${{ secrets.DOCKER_USERNAME }}/auth-users-service:.*"
          replace: "image: ${{ secrets.DOCKER_USERNAME }}/auth-users-service:${{ steps.vars.outputs.TAG }}"

          commit-message: "Update auth-users-service image to ${{ steps.vars.outputs.TAG }}"